apiVersion: v1
kind: PersistentVolume
metadata:
  name: atlantis-data
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /data/atlantis
  storageClassName: 'local'
