all:
  hosts:
    node1:
      ansible_host: 10.0.10.33
      ip: 10.0.10.33
      access_ip: 10.0.10.33
    node2:
      ansible_host: 10.0.20.31
      ip: 10.0.20.31
      access_ip: 10.0.20.31
    node3:
      ansible_host: 10.0.30.34
      ip: 10.0.30.34
      access_ip: 10.0.30.34
    cp1:
      ansible_host: 10.0.10.29
      ip: 10.0.10.29
      access_ip: 10.0.10.29
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
